[package]
name = "velox"
version = "0.1.0"
edition = "2024"
description = "Velox: A high-performance, lightweight Rust library for in-memory data processing and analytics. Featuring DataFrames, Series, CSV/JSON I/O, powerful transformations, aggregations, and statistical functions for efficient data science and engineering."
license = "MIT"
authors = ["Wali Mohammad Kadri"]
homepage = "https://github.com/Conqxeror/velox"
repository = "https://github.com/Conqxeror/velox"
keywords = ["dataframe", "series", "data-processing", "analytics", "lightweight", "high-performance", "csv", "json", "statistics", "data-science"]
categories = ["data-structures", "science", "parsing", "api-bindings"]

[lib]
path = "src/lib.rs"

[dependencies]
csv-core = "0.1"
microjson = "0.1.6"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "my_benchmark"
harness = false



