name: Code Quality Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  rust-lint-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          components: clippy, rustfmt

      - name: Run Cargo Clippy
        run: cargo clippy --all-targets -- -D warnings

      - name: Run Cargo Fmt
        run: cargo fmt --all -- --check

  
