name: Release Automation

on:
  push:
    tags:
      - 'v*' # Triggers on tags like v1.0.0, v1.0.0-beta, etc.

jobs:
  release:
    runs-on: ubuntu-latest
    environment: release

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Build Rust Release
      run: cargo build --release

    - name: Publish to Crates.io
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      run: cargo publish --token $CARGO_REGISTRY_TOKEN

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Python Build Tools
      run: pip install maturin twine

    - name: Build Python Wheel
      run: python -m maturin build --release

    - name: Publish to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: twine upload --repository pypi target/wheels/*.whl

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        registry-url: 'https://registry.npmjs.org/'

    - name: Install JS Dependencies
      run: npm install --prefix pkg

    - name: Build WASM Package
      run: wasm-pack build --target node --out-dir pkg

    - name: Publish to npmjs.com
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: npm publish --prefix pkg

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        generate_release_notes: true
